### ISSUE TITLE
Many Warnings like: Read-only state ... has been written without ack-flag with value ""

### ISSUE THREAD

**Issue by MarkusKress** [iobroker-community-adapters/ioBroker.enigma2#61]
Hello,

the enigma2 Adapter throw many warnings like:

- State "enigma2.0.Message.MESSAGE_ANSWER" has no existing object, this might lead to an error in future versions
- Read-only state "enigma2.0.enigma2.MUTED" has been written without ack-flag with value ""

80% of Log entries are only from enigma2.

**Comment by OberfragGER** [comment]
Here too. Happens sice update of js-controller.
Somehow this needs to be changed in writing the state with the ACK-flag.

adapter.setState(xxx, true);

**Comment by mcm1957** [comment]
- State "enigma2.0.Message.MESSAGE_ANSWER" has no existing object, this might lead to an error in future versions
  
  Please let us know if this problem still occures with current release (2.03 or 2.0.5)

- Read-only state "enigma2.0.enigma2.MUTED" has been written without ack-flag with value ""
  
  This is NO problem of the adapter. Most likely you write to this state by vis or a script and heve ACK=true set. The controller warns about this error now. Input states MUST be written with ack=false - otherwise the controler ignores the value change (or at east should do it)

**Comment by mcm1957** [comment]
Problem should be fixed with 2.0.2/2.0.3
No feedback received here.

let's close.

Please open a new issue if still some problmes exist.
